-- 코드를 입력하세요
# SELECT DISTINCT COUNT(NAME) AS count FROM ANIMAL_INS GROUP BY NAME;
SELECT COUNT(NAME) 
FROM (
    SELECT DISTINCT NAME
    FROM ANIMAL_INS
) AS T1
-- SELECT NAME FROM ANIMAL_INS ORDER BY 1;