-- 코드를 입력하세요
SELECT 
    CAR_ID, 
    ROUND(AVG(TIMESTAMPDIFF(DAY, START_DATE, END_DATE)+1), 1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVERAGE_DURATION >= 7
ORDER BY 2 DESC, CAR_ID DESC;

# SELECT 
#     CAR_ID, 
#     TIMESTAMPDIFF(DAY, START_DATE, END_DATE) AS AVERAGE_DURATION
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# ORDER BY CAR_ID;

# SELECT 
#     CAR_ID, 
#     START_DATE, END_DATE
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# ORDER BY CAR_ID;