-- 코드를 입력하세요
# SELECT A.*, B.*
# FROM REST_INFO A, REST_REVIEW B
# WHERE 

SELECT A.REST_ID, A.REST_NAME,  A.FOOD_TYPE, A.FAVORITES, A.ADDRESS , ROUND(AVG(IFNULL(REVIEW_SCORE, 0)), 2) SCORE
FROM REST_INFO A
JOIN REST_REVIEW B 
    ON A.REST_ID = B.REST_ID
GROUP BY A.REST_ID
HAVING ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, FAVORITES DESC

    
    
# SELECT 
#     테이블1.열1, 
#     테이블2.열2 
# FROM 
#     테이블1 
# INNER JOIN 테이블2 
#     ON 테이블1.공통_열 = 테이블2.공통_열;

# SELECT *
# FROM REST_REVIEW
# WHERE REST_ID IN (SELECT REST_ID
# FROM REST_INFO
# WHERE ADDRESS LIKE '서울%')

# SELECT REST_ID
# FROM REST_INFO
# WHERE ADDRESS LIKE '서울%'
